doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        # url: '%env(DATABASE_USER)%:%env(DATABASE_PASSWORD)%@%env(resolve:DATABASE_HOST)%:3306/%env(DATABASE_NAME)%'
        dbname:               '%env(DATABASE_NAME)%'
        host:                 '%env(DATABASE_HOST)%'
        port:                 3306
        user:                 '%env(DATABASE_USER)%'
        password:             '%env(DATABASE_PASSWORD)%'
        driver:               pdo_mysql

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: 'mariadb-10.6.22'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
            

        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/'
                        prefix: 'App\'
                        alias: App
                    SonataUserBundle: ~

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
