sonata_user:
    security_acl: false
    manager_type: orm

    class:
        user: Shared\Entity\SonataUserUser

    profile:
        default_avatar: bundles/sonatauser/default_avatar.png # Default avatar displayed if the user doesn't have one
