sonata_doctrine_orm_admin:
    templates:
        types:
            show: 
                barcode: 'admin/Barcode_show_field.html.twig'
            list:
                barcode: 'admin/Barcode_list_field.html.twig'