sonata_doctrine_orm_admin:
    templates:
        types:
            show: # or "list"
                barcode: 'admin/Barcode_show_field.html.twig'
            list: # or "list"
                barcode: 'admin/Barcode_list_field.html.twig'