name: Deploy to All-Inkl (Development)

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    environment: dev
    name: Deploy to All-Inkl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy to All-Inkl (Development)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ vars.FTP_ADDR }}
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: ${{ vars.FTP_DIR }}
          exclude: |
            **/.github*
            **/.vscode*
            **/.git*
            **/migrations*
            .env.dev*
            deploy_prod.sh
            README.md

