name: Deploy to All-Inkl (Development)

on:
  push:
    branches: [dev]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/Test.yml

  build-and-deploy:
    environment: dev
    name: Deploy to All-Inkl
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cached Primes
        id: cache-vendor-restore
        uses: actions/cache/restore@v5
        with:
          path: |
            vendor
            public/assets
            public/bundles
          key: ${{ runner.os }}-build-

      
      - name: Deploy to All-Inkl (Development)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ vars.FTP_ADDR }}
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: ${{ vars.FTP_DIR }}
          exclude: |
            .github*
            .github*/**
            .vscode*
            .vscode*/**
            .git*
            .git*/**
            migrations*
            .env.dev*
            deploy_prod.sh
            *.sql
            *.md

